<template>
	<button type="button" :class="btnClass" class="btn btn-rate" :disabled="remaining !== 0">
		<span v-if="remaining == Infinity">
			<svg style="shape-rendering: auto;" width="32px" height="32px" viewBox="0 0 100 100">
				<path fill="none" stroke="currentColor" stroke-width="5" stroke-dasharray="179.61224975585938 76.97667846679687" d="M24.3 30C11.4 30 5 43.3 5 50s6.4 20 19.3 20c19.3 0 32.1-40 51.4-40 C88.6 30 95 43.3 95 50s-6.4 20-19.3 20C56.4 70 43.6 30 24.3 30z" stroke-linecap="round">
					<animate attributeName="stroke-dashoffset" repeatCount="indefinite" dur="1s" keyTimes="0;1" values="0;256.58892822265625"></animate>
				</path>
				<!-- [ldio] generated by https://loading.io/ -->
			</svg>
		</span>
		<span v-else-if="remaining > 0">{{remaining}}</span>
		<span v-else>
			<svg width="32" height="32" fill="currentColor">
				<template v-if="type === 'plus'">
					<rect x="4" y="14" width="24" height="4" rx="2"/>
					<rect x="14" y="4" width="4" height="24" rx="2"/>
				</template>
				<template v-else-if="type === 'minus'">
					<rect x="4" y="14" width="24" height="4" rx="2"/>
				</template>
				<template v-else>
					<rect x="4" y="8" width="24" height="4" rx="2"/>
					<rect x="4" y="20" width="24" height="4" rx="2"/>
				</template>
			</svg>
		</span>
	</button>
</template>

<script>
export default {
	props: ['type','remaining'],
	data() {
		return {}
	},
	computed: {
		btnClass() {
			return 'btn-outline-' + (this.type === 'plus' ? 'danger' : (this.type === 'minus' ? 'primary' : 'default'));
		}
	}
}
</script>

<style lang="sass">
.btn-rate
	--bs-btn-border-radius: var(--btn-size)
	--bs-btn-padding-x: 0
	--bs-btn-padding-y: 0
	--bs-btn-disabled-opacity: 1

	width: var(--btn-size)
	height: var(--btn-size)
	font-weight: bold

.rate-btn-n
	--bs-btn-border-color: #546de5
	--bs-btn-hover-bg: #546de5

.rate-btn-p
	--bs-btn-border-color: #e15f41
	--bs-btn-hover-bg: #e15f41
	margin-right: 12px

.rate-btn-e
	--bs-btn-border-color: #f5cd79
	--bs-btn-hover-bg: #f5cd79
	margin-right: 12px
</style>